---

# Create a Forgejo release when a release/* branch is merged to main, by
# calling the reusable workflow in psa-systems/common.
name: Create release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  create-release:
    if: >-
      github.event.pull_request.merged == true
      && startsWith(github.event.pull_request.head.ref, 'release/v')
    uses: psa-systems/common/.forgejo/workflows/create-release.yml@main
    runs-on: ${{ vars.RUNS_ON_OPENSUSE_BASE_LATEST }}
    secrets: inherit
